server:
  port: 10001
spring:

  #过滤返回值为null 空
  jackson:
    default-property-inclusion: non_null
  application:
    name: factory
  datasource:
    url: jdbc:mysql://localhost:3306/product?characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
    password: root
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/my.keystore
    secret: tarry123
    alias: mykey
    password: tarry123